
services:
  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:latest
    command: redpanda start --overprovisioned --smp 1 --memory 512M --reserve-memory 0M --node-id 0 --check=false --kafka-addr 0.0.0.0:9092 --advertise-kafka-addr redpanda:9092
    ports:
      - "9092:9092"
      - "9644:9644"  # Admin UI
    volumes:
      - redpanda-data:/var/lib/redpanda
    healthcheck:
      test: ["CMD", "bash", "-c", "echo > /dev/tcp/localhost/9092"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  redpanda-console:
    image: docker.redpanda.com/redpandadata/console:latest
    ports:
      - "8080:8080"
    environment:
      - KAFKA_BROKERS=redpanda:9092
      - SERVER_LISTENPORT=8080
    depends_on:
      redpanda:
        condition: service_healthy

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: rides
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data


  producer:
    build:
      context: .
      dockerfile: producer/Dockerfile
    depends_on:
      redpanda:
        condition: service_healthy


  consumer:
    build:
      context: .
      dockerfile: consumer/Dockerfile
    depends_on:
      - redpanda
      - postgres
  
volumes:
  redpanda-data:
  pgdata: