
services:
  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:latest
    command: redpanda start --overprovisioned --smp 1 --memory 512M --reserve-memory 0M --node-id 0 --check=false --kafka-addr PLAINTEXT://0.0.0.0:9092
    ports:
      - "9092:9092"
      - "9644:9644"  # Admin UI
    volumes:
      - redpanda-data:/var/lib/redpanda

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: rides
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data


  producer:
    build:
      context: ./producer
    depends_on:
      - redpanda

  consumer:
    build:
      context: ./consumer
    depends_on:
      - redpanda
      - postgres
  
volumes:
  redpanda-data:
  pgdata: