services:
  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:latest
    command: redpanda start --overprovisioned --smp 1 --memory 512M --reserve-memory 0M --node-id 0 --check=false --kafka-addr 0.0.0.0:9092 --advertise-kafka-addr redpanda:9092
    ports:
      - "9092:9092"
      - "9644:9644" # Admin UI
    volumes:
      - redpanda-data:/var/lib/redpanda
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9644/v1/status/ready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redpanda-console:
    image: docker.redpanda.com/redpandadata/console:latest
    ports:
      - "8080:8080"
    environment:
      - KAFKA_BROKERS=redpanda:9092
      - SERVER_LISTENPORT=8080
    depends_on:
      redpanda:
        condition: service_healthy

  postgres:
    image: postgres:16
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "admin", "-d", "rides" ]
      interval: 10s
      timeout: 5s
      retries: 5

  producer:
    build:
      context: .
      dockerfile: producer/Dockerfile
    depends_on:
      redpanda:
        condition: service_healthy

  consumer:
    build:
      context: .
      dockerfile: consumer/Dockerfile
    depends_on:
      redpanda:
        condition: service_healthy
      postgres:
        condition: service_healthy
    env_file: .env

volumes:
  redpanda-data:
  pgdata:
